---
title: C6312 | Документация Майкрософт
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: mikeblome
ms.author: mblome
manager: jillfra
ms.openlocfilehash: 5011bd00f9fa61b646419b80afcd86dca686a005
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/23/2019
ms.locfileid: "68152372"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Предупреждение C6312: Возможно, бесконечный цикл: использование константы EXCEPTION_CONTINUE_EXECUTION в выражении фильтра исключений блока try-except  
  
 Это предупреждение указывает на использование константы `EXCEPTION_CONTINUE_EXECUTION` (или другой константы, которая принимает значение -1) в выражении фильтра структурированного обработчика исключений. Использование постоянного значения `EXCEPTION_CONTINUE_EXECUTION` может привести к бесконечному циклу. Например если исключение было вызвано оборудования, будет перезапущена инструкцию, которая вызвала исключение. Если адрес, который вызвал исключение по-прежнему поврежден, другое исключение и обрабатываться таким же образом. Это приводит к бесконечному циклу.  
  
 Явный вызов `RaiseException` не приведет непосредственно к бесконечному циклу, но будет продолжать выполнение кода в защищенном блоке. Это может быть непредвиденным и может привести к бесконечному циклу, если `RaiseException` был использован, чтобы избежать разыменования недопустимый указатель.  
  
 Как правило `EXCEPTION_CONTINUE_EXECUTION` должен возвращаться только функции, вызываемой в критерии фильтра, который имеет возможность устранить либо указатель, который вызвал исключение или основная память.  
  
## <a name="example"></a>Пример  
 В следующем коде создается данное предупреждение:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Чтобы устранить это предупреждение, используйте следующий код:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
