---
title: C6312 | Документация Майкрософт
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273920"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Warning C6312: возможные бесконечные циклы: использование константы EXCEPTION_CONTINUE_EXECUTION в выражении фильтра исключений для try-except  
  
 Это предупреждение указывает на использование константы `EXCEPTION_CONTINUE_EXECUTION` (или другой константы, результатом которой является-1) в выражении фильтра структурированного обработчика исключений. Использование значения константы `EXCEPTION_CONTINUE_EXECUTION` может привести к бесконечному циклу. Например, если аппаратное обеспечение вызвало исключение, инструкция, которая вызвала исключение, будет перезапущена. Если адрес, вызвавший исключение, по-прежнему поврежден, возникает еще одно исключение, которое будет обрабатываться таким же образом. Это приводит к бесконечному циклу.  
  
 Явный вызов метода `RaiseException` не приведет непосредственно к бесконечному циклу, но будет продолжать выполнение кода в защищенном блоке. Это может быть неожиданным, и может привести к бесконечному циклу, если `RaiseException` использовался, чтобы избежать разыменования недопустимого указателя.  
  
 Как правило, он `EXCEPTION_CONTINUE_EXECUTION` должен возвращаться только функцией, вызываемой в критерии фильтра, что может исправить либо указатель, который вызвал исключение, либо базовую память.  
  
## <a name="example"></a>Пример  
 Это предупреждение создается в следующем коде:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Чтобы исправить это предупреждение, используйте следующий код:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
