---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 7550fb74ae5fb6e4a18ae2d7391dfca3cc0546f3
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/16/2019
ms.locfileid: "72448573"
---
# <a name="c26111"></a>C26111
предупреждение C26111: вызывающему объекту не удалось снять блокировку \<lock > перед вызовом функции \<func >.

 Заметка `_Requires_lock_not_held_` накладывает предусловие, что счетчик блокировок для указанной блокировки не может быть больше нуля при вызове функции. Предупреждение C26111 выдается, когда функция не может снять блокировку перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26111, так как предусловие `_Requires_lock_not_held_` нарушается вызовом `DoNotLock` в разделе заблокировано.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
