---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: a0e91d4d8fedae14a23ed118ab592fe0842a27e8
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/07/2019
ms.locfileid: "72015669"
---
# <a name="c26111"></a>C26111
C26111 предупреждения: Вызывающему объекту не удалось снять блокировку \<lock > перед вызовом функции \<func >.

 Аннотация `_Requires_lock_not_held_` накладывает предусловие, что счетчик блокировок для указанной блокировки не может быть больше нуля при вызове функции. Предупреждение C26111 выдается, когда функция не может снять блокировку перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26111, так как предусловие `_Requires_lock_not_held_` нарушается вызовом `DoNotLock` в заблокированном разделе.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```