---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 299b2f3918af48e84f74cde5d4d783645491ef5d
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879208"
---
# <a name="c26111"></a>C26111
предупреждение C26111: вызывающему объекту не удалось снять блокировку \<> блокировки перед вызовом функции \<Func >.

 Заметка `_Requires_lock_not_held_` накладывает предусловие, что счетчик блокировок для указанной блокировки не может быть больше нуля при вызове функции. Предупреждение C26111 выдается, когда функция не может снять блокировку перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26111, так как предусловие `_Requires_lock_not_held_` нарушается вызовом `DoNotLock` в разделе заблокировано.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
