---
title: C26110
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26110
helpviewer_keywords:
- C26110
ms.assetid: d82b79ec-6d7f-438b-bd6a-da874a3e08e5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 902455e15e52a36a682197c3c265aa97f53a5161
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/23/2019
ms.locfileid: "62428135"
---
# <a name="c26110"></a>C26110
Предупреждение C26110: Вызывающий объект не удается удержать блокировку \<блокировка > до вызова функции \<func >.

 Если необходима блокировка, убедитесь, что для уточнения ли сама функция или вызывающий ее объект должен получить блокировку. Предупреждение C26110 выдается в том случае, когда есть нарушение `_Requires_lock_held_` заметки.

## <a name="example"></a>Пример
 В следующем примере выдается предупреждение C26110, так как заметка `_Requires_lock_held_` на функцию `LockRequired` том, что объект, вызывающий `LockRequired` должен получить блокировку, перед вызовом `LockRequired`. Без этой заметки `LockRequired` должен получить блокировку перед обращением к всех общих данных, защищенные блокировкой.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_held_(p->cs)

void LockRequired(DATA* p)
{
    p->d = 0;
}

void LockNotHeld(DATA* p)
{
    LockRequired(p); // Warning C26110
}
```