---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 47bb0843ab6048bbfa1b4ba881d3748a23de6dd9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449661"
---
# <a name="c6318"></a>C6318
Warning C6318: неправильное определение __try/\__except: использование константы EXCEPTION_CONTINUE_SEARCH или другой константы, результатом которой является ноль в выражении фильтра исключений. Код в блоке обработчика исключений не выполняется

 Это предупреждение означает, что при возникновении исключения в защищенном блоке этого структурированного обработчика исключений исключение не будет обработано, так как константа `EXCECPTION_CONTINUE_SEARCH` используется в выражении фильтра исключений.

 Этот код эквивалентен защищенному блоку без блока обработчика исключений, так как блок обработчика не выполняется.

## <a name="example"></a>Пример
 Это предупреждение создается в следующем коде:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Чтобы исправить это предупреждение, используйте следующий код:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>См. также раздел
 [Оператор try-except](/cpp/cpp/try-except-statement)
