---
title: Правило анализа кода CA2153 для исключений поврежденного состояния
ms.date: 02/19/2019
ms.topic: reference
author: mikejo5000
ms.author: mikejo
manager: jillfra
ms.workload:
- multiple
ms.openlocfilehash: 6297df60c7d324e38997fa882450df032f07cbba
ms.sourcegitcommit: d20ce855461c240ac5eee0fcfe373f166b4a04a9
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 05/29/2020
ms.locfileid: "84181394"
---
# <a name="ca2153-avoid-handling-corrupted-state-exceptions"></a>CA2153: Избегайте обработки исключений поврежденного состояния

|||
|-|-|
|CheckId|CA2153|
|Категория|Microsoft.Security|
|Критическое изменение|Не критическое|

## <a name="cause"></a>Причина:

[Исключения поврежденного состояния (CSE)](https://msdn.microsoft.com/magazine/dd419661.aspx) указывают на то, что в процессе существует повреждение памяти. Если перехватывать их вместо того, чтобы позволить процессу завершиться сбоем, это может привести к уязвимостям в системе безопасности, если злоумышленнику удастся поместить эксплойт в поврежденную область памяти.

## <a name="rule-description"></a>Описание правила

Исключение CSE указывает на то, что состояние процесса было повреждено, и не перехватывается системой. В сценарии с поврежденным состоянием общий обработчик перехватывает только исключение, если вы помечаете метод <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> атрибутом. По умолчанию [Среда](/dotnet/standard/clr) CLR не вызывает обработчики catch для CSE.

Наиболее надежный вариант — Разрешить аварийное завершение процесса без перехвата исключений такого рода. Даже код регистрации может позволить злоумышленникам использовать ошибки повреждения памяти.

Это предупреждение активируется при перехвате CSE с помощью общего обработчика, который перехватывает все исключения, например `catch (System.Exception e)` или `catch` без параметра исключения.

## <a name="how-to-fix-violations"></a>Устранение нарушений

Чтобы устранить это предупреждение, выполните одно из следующих действий.

- Удалите атрибут <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>. Это возвращается к поведению во время выполнения по умолчанию, когда CSE не передаются в обработчики catch.

- Удалите общий обработчик catch и используйте обработчики, перехватывающие исключения определенных типов. Это может включать CSE, предполагая, что код обработчика может безопасно их обменять (редкие).

- Повторно вызовите CSE в обработчике Catch, который передает исключение вызывающему объекту и должен привести к завершению выполняющегося процесса.

## <a name="when-to-suppress-warnings"></a>Когда следует подавлять предупреждения

Для этого правила отключать вывод предупреждений не следует.

## <a name="pseudo-code-example"></a>Пример псевдо-кода

### <a name="violation"></a>Нарушение

В приведенном ниже псевдокоде показан шаблон, обнаруживаемый этим правилом.

```csharp
[HandleProcessCorruptedStateExceptions]
// Method that handles CSE exceptions.
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-1---remove-the-attribute"></a>Решение 1. Удаление атрибута

Удаление <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> атрибута гарантирует, что исключения поврежденного состояния не будут обрабатываться методом.

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-2---catch-specific-exceptions"></a>Решение 2. перехват особых исключений

Удалите общий обработчик catch и перехватывайте только исключения определенных типов.

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (IOException e)
    {
        // Handle IOException.
    }
    catch (UnauthorizedAccessException e)
    {
        // Handle UnauthorizedAccessException.
    }
}
```

### <a name="solution-3---rethrow"></a>Решение 3. Повторное создание

Вызовите исключение заново.

```csharp
[HandleProcessCorruptedStateExceptions]
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Rethrow the exception.
        throw;
    }
}
```
